//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CashRegister.Payment
{
	using CashRegister.CashDrawers;
	using CashRegister.Printer;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class PaymentControllerImpl : IPaymentController
	{
		public virtual IEnumerable<ITransaction> Transactions
		{
			get;
			set;
		}

		public virtual IEnumerable<IPaymentProvider> PaymentProviders
		{
			get;
			set;
		}

		public virtual IBonPrinter BonPrinter
		{
			get;
			set;
		}

		public virtual void ExecuteTransaction(ITransaction transaction, IPaymentProvidorDescriptor provider)
		{
			throw new System.NotImplementedException();
		}

		public virtual ITransaction CreateTransaction()
		{
			throw new System.NotImplementedException();
		}

		public virtual void PrintTransaction(ITransaction transaction)
		{
			throw new System.NotImplementedException();
		}

	}
}

