//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CashRegister.Receipts
{
	using CashRegister.Orders;
	using CashRegister.Printer;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class ReceiptController : IReceiptController
	{
		public virtual IBonPrinter BonPrinter
		{
			get;
			set;
		}

		public virtual void Print(Receipt receipt)
		{
			throw new System.NotImplementedException();
		}

		public virtual Receipt CreateReceipt(Order order)
		{
			throw new System.NotImplementedException();
		}

	}
}

