//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CashRegister.Database
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class GenericRepository<TEntity> where TEntity : class 
    {
		internal virtual KasseApparat context
		{
			get;
			set;
		}

		internal DbSet<TEntity>
		{
			get;
			set;
		}

	}
}

