//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CashRegister.Database
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IDatabase 
	{
		/// <summary>
		/// Forbinder til databasen
		/// </summary>
		void Connect();

		/// <summary>
		/// Afbryder forbindelsen til databasen
		/// </summary>
		void Disconnect();

		/// <summary>
		/// Tager en streng med et SQL statement og returnere et object af den type som den er oprettet med
		/// </summary>
		<T> Query(object string);

	}
}

