//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CashRegister.Payment
{
	using CashRegister.CashDrawers;
	using CashRegister.Printer;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IPaymentController 
	{
		IEnumerable<IPaymentProvidorDescriptor> PaymentProvidorDescriptors { get;set; }

		void ExecuteTransaction(ITransaction transaction);

		ITransaction CreateTransaction(long amount, string description, IPaymentProvidorDescriptor paymentprovider);

		void PrintTransaction(ITransaction transaction);

	}
}

