//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CashRegister.Payment
{
	using CashRegister.CashDrawers;
	using CashRegister.Printer;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface ITransaction 
	{
		int Amount { get;set; }

		string Description { get;set; }

		int ID { get; }

		IEnumerable<ITransactionObserver> Observers { get;set; }

		TransactionStatus Status { get;set; }

		void AddObserver(ITransactionObserver observer);

	}
}

