//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CashRegister.Payment
{
	using CashRegister.CashDrawers;
	using CashRegister.Printer;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Transaction : ITransaction
	{
	    public int Amount { get; set; }
	    public string Description { get; set; }
	    public int ID { get; }
	    public IEnumerable<ITransactionObserver> Observers { get; set; }
	    public TransactionStatus Status { get; set; }

	    public virtual void AddObserver(ITransactionObserver observer)
		{
			throw new System.NotImplementedException();
		}

	}
}

