//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CashRegister.Products
{
	using CashRegister.Database;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class GroupDaoImpl : IGroupDao
	{
		public virtual void Create()
		{
			throw new System.NotImplementedException();
		}

		public virtual void Update()
		{
			throw new System.NotImplementedException();
		}

		public virtual void Delete()
		{
			throw new System.NotImplementedException();
		}

		public virtual void SelectByGroupID()
		{
			throw new System.NotImplementedException();
		}

	}
}

