//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CashRegister.Products
{
	using CashRegister.Database;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// Interface for Product management in the Database
	/// </summary>
	public interface IProductDao 
	{
		/// <summary>
		/// Insert a new Product in the database
		/// </summary>
		/// <param name="product">Product to be inserted into the database</param>
		void Insert(Product product);

		/// <param name="id">ID of the Product to return</param>
		Product SelectByID(int id);

		/// <summary>
		/// Delete a product from the database
		/// </summary>
		/// <param name="product">Product to be deleted</param>
		void Delete(Product product);

		/// <summary>
		/// Changes made to the Product is saved in the Databse
		/// </summary>
		/// <param name="product">The Product to be updated in the Database</param>
		void Update(Product product);

		/// <param name="id">ID of the ProductGroup</param>
		IEnumerable<Product> SelectByGroupID(int id);

	}
}

