//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CashRegister.Products
{
	using CashRegister.Database;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// This class is a dataholder for a specific product. 
	/// </summary>
	public class Product
	{

	    public Product(string name, int price)
	    {
	        Price = price;
	        Name = name;
	       
	    }

	    /// <summary>
		/// Price og product in danish ører
		/// </summary>
		public int Price
		{
			get;
			set;
		}

		/// <summary>
		/// Name of the product
		/// </summary>
		public string Name
		{
			get;
			set;
		}

		/// <summary>
		/// Unique ID for the product, should only be used internally to identify the specific product
		/// </summary>
		public int ID
		{
			get;
			private set;
		}

		/// <summary>
		/// Imagename or something like that
		/// </summary>
		public object Image
		{
			get;
			set;
		}

	}
}

