//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CashRegister.Products
{
	using CashRegister.Database;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// Implementation of IProductController
	/// </summary>
	public class ProductControllerImpl : IProductController
	{
		/// <summary>
		/// The ProductController uses IProductDao to interact with the Databse
		/// </summary>
		private readonly IProductDao ProductDAO;

	    private ProductControllerImpl(IProductDao DAO)
	    {
	        ProductDAO = DAO;
	    }

	    /// <param name="name">The name of the new Product, does not have to be unique</param>
	    /// <param name="price">The price of the new product, does not have to be unique</param>
	    public virtual Product CreateProduct(string name, int price)
		{
		
            //Hvornår oprettes id?? Der bliver sagt at databasen holder styr på det? 
            var newProduct = new Product(name, price);


            //newProduct.ID = ProductDAO.Insert(newProduct);



            return newProduct;
		}

	   

	    /// <param name="productgroup">The ProductGroup to find alle Products of</param>
		public virtual IEnumerable<Product> GetProductsByGroup(int productgroup)
	    {
            //
	        return ProductDAO.SelectByGroupID(productgroup);
	    }

	}
}

