//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CashRegister.Discount
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// Hvad laver interfacet 
	/// </summary>
	public interface Interface1 
	{
		/// <summary>
		/// Unikt id der bruges at iden
		/// </summary>
		int ID { get; }

		string Name { get;set; }

		/// <summary>
		/// Typer af måder vi giver discount
		/// </summary>
		IEnumerable<Enumeration1> Types { get;set; }

	}
}

