//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CashRegister.Database
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IDatabase 
	{
		void Connect();

		void Disconnect();

		T Query<T>(string SQLStatement);

	}
}

