//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using CashRegister.CashRegister.Database;
using CashRegister.DAL;

namespace CashRegister.Database
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IDatabase 
	{
		void Connect();

		void Disconnect();

		T Query<T>(string SQLStatement);

	}

    public class hat
    {
        public hat()
        {
            KasseApparat KasseContext = new KasseApparat();
            GenericRepository<Product> ProductRepository = new GenericRepository<Product>(KasseContext);
            Product test = new Product();
            test.ProductName = "Test";
            test.Discount = new Discount();
            test.DiscountId = 1;
            test.Prices = new List<Price>();
            test.OrderLists = new List<OrderList>();
            test.ProductGroups = new List<ProductGroup>();
            ProductRepository.Insert(test);
            KasseContext.SaveChanges();
        }
    }
}

