//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CashRegister.Log
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class LogFactory
	{
		/// <summary>
		/// Returns a logger instance, use a static variable to hold it 
		/// </summary>
		/// <param name="class">Insert the class that is using the logger ex typeof(ProductController)</param>
		public static ILogger GetLogger(System.Type class)
		{
			throw new System.NotImplementedException();
		}

		/// <summary>
		/// Run once in start of the program. Is used to configure how the logger shall output the log
		/// </summary>
		public static void Configure()
		{
			throw new System.NotImplementedException();
		}

	}
}

