//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CashRegister.Log
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// Wrapper for log4net
	/// </summary>
	public class Logger : ILogger
	{
		private readonly object log4net;

		public virtual void Warn(string ling)
		{
			throw new System.NotImplementedException();
		}

		public virtual void Info(string line)
		{
			throw new System.NotImplementedException();
		}

		public virtual void Error(string line)
		{
			throw new System.NotImplementedException();
		}

		public virtual void Fatal(string line)
		{
			throw new System.NotImplementedException();
		}

		public virtual void Debug(string line)
		{
			throw new System.NotImplementedException();
		}

		internal Logger(System.Type type)
		{
		}

	}
}

