//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CashRegister.Sales
{
	using CashRegister.Orders;
	using CashRegister.Payment;
	using CashRegister.Products;
	using CashRegister.Receipts;
	using CashRegister.ShoppingLists;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class SalesController : ISalesController
	{
		public virtual IPaymentController PaymentController
		{
			get;
			set;
		}

		public virtual IShoppingListController ShoppingListController
		{
			get;
			set;
		}

		public virtual IReceiptController ReceiptController
		{
			get;
			set;
		}

		public virtual IOrderController OrderController
		{
			get;
			set;
		}

		public virtual void AddProductToShoppingList(Product product)
		{
			throw new System.NotImplementedException();
		}

		public virtual void BuyShoppingList()
		{
			throw new System.NotImplementedException();
		}

		public virtual void RemoveProductFromShoppingList(Product product)
		{
			throw new System.NotImplementedException();
		}

		public virtual void ClearShoppingList()
		{
			throw new System.NotImplementedException();
		}

	}
}

