//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CashRegister.Sales
{
	using CashRegister.Orders;
	using CashRegister.Payment;
//	using CashRegister.Products;
	using CashRegister.Receipts;
    using CashRegister.Database;
    using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// Controls sales
	/// </summary>
	public interface ISalesController 
	{
		/// <summary>
		/// Adds a product to the current order
		/// </summary>
		void AddProductToOrder(Product product);

        /// <summary>
	    /// Returns the current order
	    /// </summary>
	    OrderList GetCurrentOrder();

        /// <summary>
        /// Remove a product from orderlist
        /// </summary>
        void RemoveProductFromOrder(Product product);

	    /// <summary>
	    /// Prints an order
	    /// </summary>
	    void CreateAndPrintReceipt(OrderList order);


        /// <summary>
        /// clear orderlist
        /// </summary>
        void ClearOrder();

		/// <summary>
		/// Starts a new Orderlist with a new id
		/// </summary>
		void StartNewOrder();

		/// <summary>
		/// Cancel transactions, clear orderlist
		/// </summary>
		void CancelOrder();

		/// <summary>
		/// Save an Order as incomplete
		/// </summary>
		void SaveIncompleteOrder();

		/// <summary>
		/// Starting payment on a Orderlist
		/// </summary>
		void StartPayment(IPaymentProvidorDescriptor provider, long amountToPay);

		/// <summary>
		/// Get info on the amount missing on the orderlist
		/// </summary>
		long MissingPaymenOnOrder();

		/// <summary>
		/// Add an transaction to the order
		/// </summary>
		void AddTransaction(Transaktion trans);

	    /// <summary>
	    /// Gets a list of all incomplete orders by default current data (or within a certain date or time)
	    /// </summary>
	    List<OrderList> GetIncompleteOrders(DateTime start, DateTime end);

        /// <summary>
        /// Get an incomplete order
        /// </summary>
        void RetrieveIncompleteOrder(int OrderId, DateTime Date1, DateTime Date2);

	}
}

