//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CashRegister.Sales
{
	using CashRegister.Orders;
	using CashRegister.Payment;
	//using CashRegister.Products;
	using CashRegister.Receipts;
	using CashRegister.Database;
   // using CashRegister.Payment;
    using CashRegister.DAL;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// Controls sales
	/// </summary>
	public class SalesController : ISalesController
	{
		/// <summary>
		/// Hold the current order
		/// </summary>
		private OrderList CurrentOrder
		{
			get;
			set;
		}

		public virtual IReceiptController ReceiptController
		{
			get;
			set;
		}

		public virtual IOrderController OrderController
		{
			get;
			set;
		}

        /// <summary>
		/// Contructor - Calls StartNewOrder()
		/// </summary>
		public SalesController(IOrderController Ordercontroller, IReceiptController Receiptcontroller)
        {
            OrderController = Ordercontroller;
            ReceiptController = Receiptcontroller;
            StartNewOrder();
        }

	    /// <summary>
	    /// Returns the current order
	    /// </summary>
	  public virtual OrderList GetCurrentOrder()
	    {
	        return CurrentOrder;
	    }

        /// <summary>
        /// Add a product to an orderlist
        /// </summary>
        public virtual void AddProductToOrder(Product product)
		{
			CurrentOrder.Products.Add(product);
		}

        /// <summary>
        /// Prints an order
        /// </summary>
        public virtual void CreateAndPrintReceipt(OrderList order)
	    {
	      var print= ReceiptController.CreateReceipt(order);
          ReceiptController.Print(print);
        }


        /// <summary>
        /// Remove a product from orderlist
        /// </summary>
        public virtual void RemoveProductFromOrder(Product product)
		{
		    CurrentOrder.Products.Remove(product);
		}

		/// <summary>
		/// clear orderlist
		/// </summary>
		public virtual void ClearOrder()
		{
		    OrderList tmp = CurrentOrder;
		    OrderController.ClearOrder(ref tmp);
		}

		/// <summary>
		/// Starts a new Orderlist with a new id
		/// </summary>
		public virtual void StartNewOrder()
		{
		   CurrentOrder = OrderController.CreateOrder();
		}

	    

		/// <summary>
		/// Cancel transactions, clear orderlist
		/// </summary>
		public virtual void CancelOrder()
		{
		    foreach (var Transaktion in CurrentOrder.Transaktions)
		    {
		        CurrentOrder.Transaktions.Remove(Transaktion);
		    }

		    OrderList tmp = CurrentOrder;
            OrderController.ClearOrder(ref tmp);
            StartNewOrder();
		}

		/// <summary>
		/// Save an Order as incomplete
		/// </summary>
		public virtual void SaveIncompleteOrder()
		{
		  CurrentOrder.Status.StatusName="Incomplete";
            OrderController.SaveOrder(CurrentOrder);
            StartNewOrder();
		}

	    /// <summary>
	    /// Starting payment on a Orderlist
	    /// </summary>
	    public virtual void StartPayment(IPaymentProvidorDescriptor provider, long amountToPay)
	    {
	        if (amountToPay > MissingPaymenOnOrder())
	        {
	            Console.WriteLine("Amount Too Large");
	            throw new System.InvalidCastException();
	        }
	        PaymentController.CreateTransaction(amountToPay, "Bla", provider);
	        if (amountToPay == 0)
	        {
                CurrentOrder.Status.StatusName = "Complete";
	            OrderController.SaveOrder(CurrentOrder);
                StartNewOrder();
	        }
	    }

		/// <summary>
		/// Get info on the amount missing on the orderlist
		/// </summary>
		public virtual long MissingPaymenOnOrder()
		{
		   long missingAmount = OrderController.MissingAmount(CurrentOrder);
		   return missingAmount;
		}

		/// <summary>
		/// Adds an transaction to an order
		/// </summary>
		public virtual void AddTransaction(Transaktion trans)
		{
			CurrentOrder.Transaktions.Add(trans);
		}

		/// <summary>
		/// Gets a list of all incomplete orders by default current data (or within a certain date or time)
		/// </summary>
		public virtual List<OrderList> GetIncompleteOrders(DateTime start, DateTime end)
		{
            List<OrderList> NewList = new List<OrderList>();
            SalesUnitOfWork SalesWork = new SalesUnitOfWork(new CashRegisterContext());
		    var Liste = SalesWork.OrderListRepository.Get(OrderList => OrderList.Status.StatusName == "Incomplete" );

		    foreach (OrderList order in Liste)
		    {
		        if (order.OrderDate >= start && order.OrderDate <= end)
                    NewList.Add(order);
		    }
            return NewList;
  
		}

	    /// <summary>
	    /// Get an incomplete order
	    /// </summary>
	    public virtual void RetrieveIncompleteOrder(int OrderId, DateTime Date1, DateTime Date2)
	    {

	        List<OrderList> ListOfIncompletes = GetIncompleteOrders(Date1, Date2);

	        foreach (OrderList orders in ListOfIncompletes)
	        {
	            if (OrderId == orders.OrderId)
	                CurrentOrder = orders;
	        }
	    }

	}

    public class PaymentController
    {
        public static void CreateTransaction(long amountToPay, string bla, IPaymentProvidorDescriptor provider)
        {
            throw new NotImplementedException();
        }
    }
}

