//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CashRegister.ShoppingLists
{
	using CashRegister.Products;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class ShoppingListItem
	{
		public virtual Product Product
		{
			get;
			set;
		}

	}
}

