//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CashRegister.Orders
{
	using CashRegister.Database;
	using CashRegister.Products;
	using CashRegister.ShoppingLists;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IOrderController 
	{
		/// <summary>
		/// Createas an order fra the shopping list
		/// </summary>
		void CreateOrder();

		/// <summary>
		/// Gets order by ID
		/// </summary>
		Order GetOrderByID(int id);

		/// <summary>
		/// Get the last n orders
		/// </summary>
		/// <param name="n">How many orders we wish to ha returned</param>
		void GetNLastOrders(int n);

	}
}

