//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CashRegister.Orders
{
	using CashRegister.Database;
	using CashRegister.Products;
	using CashRegister.ShoppingLists;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IOrderDao 
	{
		/// <summary>
		/// Being able to delete an order from the database
		/// </summary>
		void Delete(Order order);

		/// <summary>
		/// Update an order in the database
		/// </summary>
		void Update(Order order);

		/// <summary>
		/// Being able to insert an order to the database
		/// </summary>
		void Insert(Order order);

		/// <summary>
		/// Selecting an Product by ID in from the database
		/// </summary>
		Order SelectByID(int id);

	}
}

