//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Net.Sockets;

namespace CashRegister.Orders
{
	using CashRegister.Database;
	using CashRegister.Products;
	using CashRegister.ShoppingLists;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class OrderController : IOrderController
	{
		public virtual IOrderDao OrderDao
		{
			get;
			set;
		}

		/// <summary>
		/// Createas an order with the id from the last order+1
		/// </summary>
		public virtual void CreateOrder()
		{
            int lastorder=GetNLastOrders(1);
            List<Product> OrderList = new List<Product>();
            OrderList.Add(Description);
            OrderList.Add(ID);
            
            OrderList.Add(Value);

        }

		/// <summary>
		/// Gets order by ID
		/// </summary>
		public virtual Order GetOrderByID(int id)
		{
			SELECT * 
		}

		/// <summary>
		/// Get the last n orders
		/// </summary>
		/// <param name="n">How many orders we wish to ha returned</param>
		public virtual void GetNLastOrders(int n)
		{
            List<Order> OrderReceived = new List<Order>();
            OrderDao.SelectByID()
            OrderReceived.Add();
        }

	}
}

