//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CashRegister.Orders
{
	using CashRegister.Database;
	//using CashRegister.Products;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Order
	{
		/// <summary>
		/// The orderID
		/// </summary>
		public virtual object ID
		{
			get;
			set;
		}

		/// <summary>
		/// The total value of items in the order
		/// </summary>
		public virtual object Value
		{
			get;
			set;
		}

		/// <summary>
		/// Description of the order
		/// </summary>
		public virtual object Description
		{
			get;
			set;
		}

		public virtual IEnumerable<OrderItem> OrderItems
		{
			get;
			set;
		}

	}
}

