//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CashRegister.Products.Groups
{
	using CashRegister.Database;
	using CashRegister.Products;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IGroupDao 
	{
		void Create();

		void Update();

		void Delete();

		void SelectByGroupID();

	}
}

