//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CashRegister.CashDrawers
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class CashDrawer : ICashDrawer
	{
		/// <summary>
		/// Opens the drawer of the CashDrawer
		/// </summary>
		public virtual void Open()
		{
			throw new System.NotImplementedException();
		}

	}
}

