//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CashRegister.Printer
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class BonPrinter : IBonPrinter
	{
		public virtual void PrintString(string str)
		{
			throw new System.NotImplementedException();
		}

	}
}

