//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CashRegister.Printer
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// Interface to a printing device
	/// </summary>
	public interface IPrinter 
	{
		/// <summary>
		/// Adds a string to the print document
		/// </summary>
		/// <param name="str">str is added to the print document</param>
		void AddTo(string str);

		/// <summary>
		/// Initiates a print
		/// </summary>
		void Print();

	}
}

