//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CashRegister.Printer
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// Implementation of a receipt printer
	/// </summary>
	public class RecieptPrinter : IPrinter
	{
		/// <summary>
		/// Adds a string to a print document
		/// </summary>
		/// <param name="str">str is added to the print document</param>
		public virtual void AddTo(string str)
		{
			throw new System.NotImplementedException();
		}

		/// <summary>
		/// Initiates a print from the reciept printer
		/// </summary>
		public virtual void Print()
		{
			throw new System.NotImplementedException();
		}

	}
}

