//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CashRegister.Log
{
    public abstract class LogFactory
	{
		/// <summary>
		/// Returns a logger instance, use a static variable to hold it 
		/// </summary>
		/// <param name="type">Insert the class that is using the logger ex typeof(ProductController)</param>
		public static ILogger GetLogger(System.Type type)
		{
			return new Logger(type);
		}

		/// <summary>
		/// Run once in start of the program. Is used to configure how the logger shall output the log
		/// </summary>
		public static void Configure()
		{
			Logger.Configure();
		}

	}
}

