//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CashRegister.Orders
{
	using CashRegister.Database;
	using CashRegister.Products;
	using CashRegister.ShoppingLists;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class OrderDao : IOrderDao
	{
		public virtual IDatabase Database
		{
			get;
			set;
		}

		public virtual void Delete(Order order)
		{
			throw new System.NotImplementedException();
		}

		public virtual void Update(Order order)
		{
			throw new System.NotImplementedException();
		}

		public virtual void Insert(Order order)
		{
			throw new System.NotImplementedException();
		}

		public virtual Order SelectByID(int id)
		{
			throw new System.NotImplementedException();
		}

	}
}

