//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CashRegister.Orders
{
	using CashRegister.Database;
	using CashRegister.Products;
	using CashRegister.ShoppingLists;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class OrderController : IOrderController
	{
		public virtual IOrderDao OrderDao
		{
			get;
			set;
		}

		public virtual void CreateOrder(ShoppingList shoppinglist)
		{
			throw new System.NotImplementedException();
		}

		public virtual Order GetOrderByID(int id)
		{
			throw new System.NotImplementedException();
		}

		/// <param name="n">How many orders we wish to ha returned</param>
		public virtual void GetNLastOrders(int n)
		{
			throw new System.NotImplementedException();
		}

	}
}

