//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CashRegister.Orders
{
	using CashRegister.Database;
	using CashRegister.Products;
	using CashRegister.ShoppingLists;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Order
	{
		public virtual object ID
		{
			get;
			set;
		}

		public virtual object Value
		{
			get;
			set;
		}

		public virtual object Description
		{
			get;
			set;
		}

		public virtual IEnumerable<OrderItem> OrderItems
		{
			get;
			set;
		}

	}
}

